<a href="https://colab.research.google.com/github/tiutiutiu666/SC_Team-Assignment-Chapter-2-Machine-Learning-and-Deep-Learning/blob/main/MACHINE%20LEARNING%20%5BCase%20%231%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Chapter 2 - MACHINE LEARNING [Case #1]
Startup Campus, Indonesia - `Artificial Intelligence (AI)` (Batch 7)
* Dataset: SC_HW1_bank_data
* Libraries: Pandas, Numpy, Scikit-learn
* Objective: Classification with Supervised Machine Learning Models

`PERSYARATAN` Semua modul (termasuk versi yang sesuai) sudah di-install dengan benar.
<br>`CARA PENGERJAAN` Lengkapi baris kode yang ditandai dengan **#TODO**.
<br>`TARGET PORTFOLIO` Peserta mampu membandingkan akurasi klasifikasi dari berbagai model *supervised learning*.

### Import Library

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Read Dataset

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')
#df.columns
df.head(5)

RowNumber  CustomerId Geography  Gender  Age  Tenure    Balance  \
0          1    15634602    France  Female   42       2       0.00   
1          2    15647311     Spain  Female   41       1   83807.86   
2          3    15619304    France  Female   42       8  159660.80   
3          4    15701354    France  Female   39       1       0.00   
4          5    15737888     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [ ]:
# TODO: Hilangkan kolom yang tidak relevan untuk pemodelan
#df = df[[...]].copy()
df = df.drop(columns=['RowNumber', 'CustomerId'])
df.head(10)

Geography  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0    France  Female   42       2       0.00              1          1   
1     Spain  Female   41       1   83807.86              1          0   
2    France  Female   42       8  159660.80              3          1   
3    France  Female   39       1       0.00              2          0   
4     Spain  Female   43       2  125510.82              1          1   
5     Spain    Male   44       8  113755.78              2          1   
6    France    Male   50       7       0.00              2          1   
7   Germany  Female   29       4  115046.74              4          1   
8    France    Male   44       4  142051.07              2          0   
9    France    Male   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0  
5               0        149756.71       1  
6               1         10062.80       0  
7               0        119346.88       1  
8               1         74940.50       0  
9               1         71725.73       0

### Preprocessing

In [ ]:
# TODO: Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
dummies1 = pd.get_dummies(df[['Gender']], drop_first=True, dtype=int)
dummies2 = pd.get_dummies(df[['Geography']],dtype=int)
df = pd.concat([df,dummies1, dummies2], axis=1).drop(columns=['Gender', 'Geography'], axis=1)
df

Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      42       2       0.00              1          1               1   
1      41       1   83807.86              1          0               1   
2      42       8  159660.80              3          1               0   
3      39       1       0.00              2          0               0   
4      43       2  125510.82              1          1               1   
...   ...     ...        ...            ...        ...             ...   
9995   39       5       0.00              2          1               0   
9996   35      10   57369.61              1          1               1   
9997   36       7       0.00              1          0               1   
9998   42       3   75075.31              2          1               0   
9999   28       4  130142.79              1          1               0   

      EstimatedSalary  Exited  Gender_Male  Geography_France  \
0           101348.88       1            0                 1   
1           112542.58       0            0                 0   
2           113931.57       1            0                 1   
3            93826.63       0            0                 1   
4            79084.10       0            0                 0   
...               ...     ...          ...               ...   
9995         96270.64       0            1                 1   
9996        101699.77       0            1                 1   
9997         42085.58       1            0                 1   
9998         92888.52       1            1                 0   
9999         38190.78       0            0                 1   

      Geography_Germany  Geography_Spain  
0                     0                0  
1                     0                1  
2                     0                0  
3                     0                0  
4                     0                1  
...                 ...              ...  
9995                  0                0  
9996                  0                0  
9997                  0                0  
9998                  1                0  
9999                  0                0  

[10000 rows x 12 columns]

In [ ]:
# TODO: Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
X = df.drop(['Exited'], axis=1)
y = df['Exited']

In [ ]:
scaler = MinMaxScaler() # TODO: Lakukan scaling atau normalisasi
X_transform = scaler.fit_transform(X)

In [ ]:
# Bagian ini digunakan jika Anda melakukan scaling atau normalisasi.
# Jika tidak, code ini bisa dilewati dan diganti dengan code yang ada di dalam comment.

X_transform = pd.DataFrame(X_transform, columns = X.columns)
X_transform.head()
# X_transform = X.copy()

Age  Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0  0.324324     0.2  0.000000       0.000000        1.0             1.0   
1  0.310811     0.1  0.334031       0.000000        0.0             1.0   
2  0.324324     0.8  0.636357       0.666667        1.0             0.0   
3  0.283784     0.1  0.000000       0.333333        0.0             0.0   
4  0.337838     0.2  0.500246       0.000000        1.0             1.0   

   EstimatedSalary  Gender_Male  Geography_France  Geography_Germany  \
0         0.506735          0.0               1.0                0.0   
1         0.562709          0.0               0.0                0.0   
2         0.569654          0.0               1.0                0.0   
3         0.469120          0.0               1.0                0.0   
4         0.395400          0.0               0.0                0.0   

   Geography_Spain  
0              0.0  
1              1.0  
2              0.0  
3              0.0  
4              1.0

### Train-Test Split

In [ ]:
X_train ,X_test, y_train, y_test = tts(X_transform, y, test_size = 0.25, random_state = 123)

### Model #1

#### Pertanyaan: Jelaskan secara singkat model #1 yang Anda gunakan.

**Logistic Regression**

Logistic Regression adalah model machine learning yang digunakan untuk data yang sifatnya kategori atau diskrit. Ketika kita ingin mengetahui/mengkategorikan kemungkinan suatu peristiwa terjadi atau tidak. Misalnya, memprediksi apakah seorang karyawan telah keluar dari perusahaan atau tidak.

In [ ]:
from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model1 = LogisticRegression()
params =  {
    'C': [0.5,1.0,1.5,2.0],
    "tol": [0.1,0.01,0.001],
    'solver': ['sag']
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator= model1,
    param_grid= params,
    scoring = 'accuracy',
    n_jobs = 10,
    cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
)

grid.fit(X_train,y_train)
grid.best_params_

{'C': 0.5, 'solver': 'sag', 'tol': 0.1}

In [ ]:
y_pred = grid.predict(X_test) # TODO: Lakukan evaluasi untuk model #1


print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.98      0.89      1983
           1       0.69      0.17      0.27       517

    accuracy                           0.81      2500
   macro avg       0.75      0.57      0.58      2500
weighted avg       0.79      0.81      0.76      2500


[[1943   40]
 [ 430   87]]

0.812


### Model #2

#### Pertanyaan: Jelaskan secara singkat model #2 yang Anda gunakan.

**Gradient Boosting Classifier**

Gradient Boosting Classifier adalah metode machine learning dengan cara menggunakan model lemah untuk membuat sebuah model ensembel yang lebih kuat. Karena metaode ini menggabungkan banyak model yang lebih sederhana (disebut weak learners), maka akan menghasilkan model yang jauh lebih kompleks dan akurat

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}

# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model2 = GradientBoostingClassifier()
params2 = {
    'n_estimators':[1, 2, 5, 10, 20, 50, 100],
    'learning_rate':[0.2, 0.1, 0.05, 0.01],
    'max_depth':[3, 4, 5]
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid2 = GridSearchCV(
    estimator= model2,
    param_grid= params2,
    scoring = 'accuracy',
    n_jobs = 10,
    cv = 10
)

grid2.fit(X_train,y_train)
grid2.best_params_

{'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100}

In [ ]:
# TODO: Lakukan evaluasi untuk model #2
y_pred2 = grid2.predict(X_test)

print(classification_report(y_test, y_pred2))
print("")
print(confusion_matrix(y_test, y_pred2))
print("")
print(accuracy_score(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1983
           1       0.78      0.52      0.62       517

    accuracy                           0.87      2500
   macro avg       0.83      0.74      0.77      2500
weighted avg       0.86      0.87      0.86      2500


[[1907   76]
 [ 250  267]]

0.8696


### Model #3

#### Pertanyaan: Jelaskan secara singkat model #3 yang Anda gunakan.

**Random Forest Classifier**

Random Forest Classifier adalah metode machine learning yang bekerja dengan memilih seluruh kemungkinan yang ada untuk menjadi sebuah root node, lalu menghitung seluruh kemungkinan dengan cara menggunakan model lemah untuk membuat sebuah model ensembel yang akan terbentuk berdasarkan root node yang dipilih.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()
params3 = {
    'n_estimators':[50, 100, 150],
    'criterion':['gini', 'entropy'],
    'random_state':[8, 24],
    'max_depth':[None, 8, 12]
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid3 = GridSearchCV(
    estimator = model3,
    param_grid = params3,
    scoring = 'accuracy',
    n_jobs = 10,
    cv = 10
)

grid3.fit(X_train,y_train)
grid3.best_params_

{'criterion': 'entropy',
 'max_depth': 12,
 'n_estimators': 100,
 'random_state': 24}

In [ ]:
y_pred3 = grid3.predict(X_test)

print(classification_report(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1983
           1       0.79      0.45      0.58       517

    accuracy                           0.86      2500
   macro avg       0.83      0.71      0.75      2500
weighted avg       0.85      0.86      0.85      2500

[[1919   64]
 [ 282  235]]
0.8616


### Conclusion

#### Pertanyaan: Tarik kesimpulan model mana yang terbaik beserta alasannya?

Berdasarkan hasil evaluasi model, dapat terlihat bahwa Random Forest Classifier dan Gradient Boosting Classifier menunjukkan performa yang lebih baik dibandingkan dengan Logistic Regression. Kedua model ini berhasil mencapai accuracy score yang lebih tinggi menunjukkan bahwa kemampuannya dalam mengklasifikasikan data dengan lebih akurat. Hal ini menunjukkan bahwa model-model kompleks yang dibangun secara bertahap seperti Random Forest dan Gradient Boosting lebih efektif dalam menangani dataset yang kompleks dan non-linear dibandingkan dengan model linier seperti Logistic Regression.

Dan dari hasil accuracy score, dapat disimpulkan bahwa Gradient Boosting Classifier merupakan model yang terbaik dari ketiganya, karena GBC menggabungkan banyak model. Hal ini membuat GBC mampu mengurangi bias yang mungkin terjadi. Selain itu, GBC juga melakukan ensemble learning, dimana akan membantu mengurangi varians, sehingga model menjadi lebih stabil dan kurang rentan terhadap overfitting.


### Scoring
Total `#TODO` = 13
<br>Checklist:

- [ ] Hilangkan kolom yang tidak relevan untuk pemodelan
- [ ] Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
- [ ] Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
- [ ] Lakukan scaling atau normalisasi
- [ ] Jelaskan secara singkat model #1 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #1)
- [ ] Lakukan evaluasi untuk model #1
- [ ] Jelaskan secara singkat model #2 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #2)
- [ ] Lakukan evaluasi untuk model #2
- [ ] Jelaskan secara singkat model #3 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #3)
- [ ] Lakukan evaluasi untuk model #3

### Additional readings
- N/A

### Copyright © 2024 Startup Campus, Indonesia
* You may **NOT** use this file except there is written permission from PT. Kampus Merdeka Belajar (Startup Campus).
* Please address your questions to mentors.